### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by wunderbaresnet** [sjelfull/craft3-calendarlinks#11]
Hi there.
I am a happy user of this (rather oldish) plugin - any plans to make it ready for Craft 4?
Thanks.

**Comment by engram-design** [comment]
We've recently acquired this plugin from the Superbig team. Read our [blog post](https://verbb.io/blog/some-plugins-from-superbig) for more details.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/calendar-links/releases/tag/3.0.0)
