### ISSUE TITLE
Error Adding Event to Yahoo Calendar: "Upstream connect error or disconnect/reset before headers"

### ISSUE THREAD

**Issue by Siyabulela** [sjelfull/craft3-calendarlinks#15]
### Describe the bug

When attempting to add an event to Yahoo Calendar using the `verbb/calendar-links` plugin, I encountered an error. 

  **Expected Behavior:** I expected the event to be added to my Yahoo Calendar without any issues.  **Actual Behavior:** Instead, I encountered the following error:

**Actual Behavior:**
Instead, I encountered the following error: `"Upstream connect error or disconnect/reset before headers. Reset reason: connection termination."`

### Steps to reproduce

1. Navigate to the event on the website. 
2. Click on the "Add to Calendar" button. 
3. Select "Yahoo Calendar" as the calendar application. 
4. The page redirects to Yahoo Calendar, but an error occurs. 

### Craft CMS version

4.5.11

### Plugin version

3.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
I'm getting all sorts of different messages from them, and from a quick search, seems like a generic error message when their systems are down. I can't even add calendar items to the Yahoo Calendar UI itself.

**Comment by engram-design** [comment]
Hmm, so seems related to using spaces or other special characters in the URL.

Not working: https://calendar.yahoo.com/?v=60&ST=20231123T213141Z&ET=20231123T233141Z&title=Test%20event
Working: https://calendar.yahoo.com/?v=60&ST=20231123T213141Z&ET=20231123T233141Z&title=Test-event

But I still think its a larger issue. Paid services like AddThis also flag downtime: https://www.addevent.com/create/down/yahoo?title=An%20amazing%20event%20%F0%9F%A5%B3&date_start=20230413T080000&date_end=20230413T100000&duration=&description=This%20is%20an%20event%20description.%20Add%20information%20about%20your%20event%20here%21%20%F0%9F%91%8B%0A%0ALorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit.%20Sed%20tempor%20vehicula%20metus%2C%20ac%20rutrum%20nulla%20finibus%20et.%20Nunc%20egestas%20pellentesque%20quam%20in%20feugiat.%20Aenean%20scelerisque%20lacus%20sed%20eros%20aliquet%20dignissim.%20Aliquam%20erat%20volutpat.%20Etiam%20a%20metus%20interdum%2C%20egestas%20est%20sed%2C%20gravida%20nisl.%20Duis%20fringilla%20est%20sed%20arcu%20tincidunt%20semper.%20Morbi%20rutrum%20nisl%20nunc%2C%20quis%20tempus%20dui%20pharetra%20tristique.%20Vestibulum%20a%20dolor%20sit%20amet%20nunc%20venenatis%20convallis%20non%20tempus%20lorem.%0A%0A------%0A%0APowered+by+addevent.com+%0AShare+your+next+event+with+us%21%0A&location=https%3A%2F%2Fzoom.us%2Fmeeting-link&linktype=2

<img width="742" alt="image" src="https://github.com/verbb/calendar-links/assets/1221575/544b0389-b59b-45ce-96e1-a8a511fd2a2a">

**Comment by Siyabulela** [comment]
Thank you for responding. I see this is not the Calendar-links issue
