### ISSUE TITLE
All Day Event Request

### ISSUE THREAD

**Issue by jeffaglenn** [sjelfull/craft3-calendarlinks#2]
I needed the ability to have an event not be bound to a start and end time just start and end dates. No matter what I tried I kept getting errors because it required time. I ended up editing the files that generate the URLs to remove the time but it might be nice to have the option to have all day events. It looks as if Google and iCal automatically mark an event as all day if there is no time in the URL. Not sure about Yahoo - don't have an account.

e.g. `&dates=20180802/20180805`

**Comment by alies-dev** [comment]
@jeffaglenn 
It's pretty easy to fix: [update a dependency](https://github.com/sjelfull/craft3-calendarlinks/issues/7) and update API of this package (probably add a new argument):
https://github.com/sjelfull/craft3-calendarlinks/blob/ef7846d783ff33ccd6110b4b441ac1b83b5d22ac/src/services/CalendarLinksService.php#L40-L43

feel free to create a PR :)

**Comment by engram-design** [comment]
Added in [2.0.1](https://github.com/verbb/calendar-links/releases/tag/2.0.1)
