### ISSUE TITLE
Customizable Filename

### ISSUE THREAD

**Issue by scuocere** [sjelfull/craft3-calendarlinks#3]
I would like to be able to define a custom file name for the ical file.

**Comment by sjelfull** [comment]
I don't think this is possible with the underlying library.

**Comment by alies-dev** [comment]
@scuocere 
@sjelfull 
dimply use `download` attr:
```html
<a href="{{ link.ics() }}" download="youCustomFilename.ics">Ical</a>
```


If it's not working for some reason, you can specify `Content-Disposition ` [header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) as we already for `charset` header: `<a href="data:text/calendar;charset=utf8"; ...>`

But I think `download` attr is much more flexible solution
