### ISSUE TITLE
DateTime / String issues in tempates

### ISSUE THREAD

**Issue by artmem** [sjelfull/craft3-calendarlinks#6]
I'm trying to use this plugin on a site where I have separate Craft date fields for the date and the time. No matter how I try to format the dates, I get an error "must be an instance of DateTime, string given". What is the proper way to specify the start and end of an event using Craft date fields?

**Comment by sjelfull** [comment]
Could you show me your template code? You are not passing DateTime instances. Most likely you are formatting your fields with the `|date` filter or somehow turning the date fields into a string.

**Comment by artmem** [comment]
I started with this:

{% set start %}{{ entry.startDate|date('Ymd') }}T{{ entry.startTime|date('His')}}{% endset %}
{% set end %}{{ entry.startDate|date('Ymd') }}T{{ entry.endTime|date('His')}}{% endset %}
{% set link = craft.calendarLinks.create({
    text: 'Test',
    from: start,
    to: end,
}) %}

I also tried it without the |date filters: 

{% set start %}{{ entry.startDate }}T{{ entry.startTime }}{% endset %}
{% set end %}{{ entry.startDate }}T{{ entry.endTime }}{% endset %}
{% set link = craft.calendarLinks.create({
    text: 'Test',
    from: start,
    to: end,
}) %}

But with that code, i get this error: "Object of class DateTime could not be converted to string".

I need to combine my startDate and startTime date fields to get the 'from' part, and startDate and endTime fields to get the 'to' portion.

**Comment by sjelfull** [comment]
The problem here is that your turning your `DateTime` instances into strings, as the error points out.

Try this instead: `{% set start = entry.startDate|date_modify(entry.startTime|date('H:i:s')) %}`

This will take the date, and then modify it to the correct time.

**Comment by stevehurst** [comment]
I'm having a similar issue trying to change the date field's timezone. Any modification turns the variable into a string. How would you augment the above code to change the timezone of the date fields? I have a custom timezone field with values.

```
                    {% set dateTimezone = 'US/Central' %}
                    {% if entry.timezone|length %}
                        {% set dateTimezone = entry.timezone %}
                    {% endif %}
                        {% set dateFrom = item.startDate|date('Y-m-d H:i:s', dateTimezone) %}
                        {% set dateTo = item.endDate|date('Y-m-d H:i:s', dateTimezone) %}
                        {% set addToCalendarLink = craft.calendarLinks.create({
                            text: item.title,
                            from:dateFrom,
                            to:dateTo,
                        }) %}
                        <li><a href="{{ addToCalendarLink.ics() }}" download="{{ item.title|replace({' ': ''}) }}.ics" class="link-add-calendar">Add to Calendar</a></li>
```

**Comment by sjelfull** [comment]
@stevehurst The reason is your using the `date` filter, which will format the instance into a string of your chosen format.

I'm not sure if there is a way to do it without some custom module code.
