### ISSUE TITLE
Update spatie/calendar-links version

### ISSUE THREAD

**Issue by alies-dev** [sjelfull/craft3-calendarlinks#7]
Reason: it has [allDay event feature](https://github.com/sjelfull/craft3-calendarlinks/issues/2) and a lot of fixes:

https://github.com/spatie/calendar-links/blob/master/CHANGELOG.md

`spatie/calendar-links` uses semver, that means you can use 

```
"spatie/calendar-links": "^1.0.0"
```

instead of 

```
"spatie/calendar-links": "~1.0.0"
```

**Comment by sjelfull** [comment]
Thanks!
