### ISSUE TITLE
Add webOutlook method

### ISSUE THREAD

**Issue by sjelfull** [sjelfull/craft3-calendarlinks#9]

**Comment by engram-design** [comment]
Already supported via:

```twig
<a href="{{ link.webOutlook() }}">webOutlook</a>
```

**Comment by engram-design** [comment]
My mistake! I thought it was a straight-thru to `Spatie\CalendarLinks\Link`.

Added in [2.0.2](https://github.com/verbb/calendar-links/releases/tag/2.0.2)
